### PR TITLE
GHI-381 Fixed cancelling issue

### LINKED ISSUE #381: When canceling safe creation we can't start it again without restarting the app

### PR DESCRIPTION
**Pull request by DmitryBespalov**
- Small refactoring of state logic in `SafeCreationViewController`
- Rewrote `EventPublisher` guts using DispatchQueue instead of OperationQueue
- Fixed the issue: the event publishing was stuck because of the handling event code was synchronous. Events were blocked. Added dispatching of each event handler to an async queue
- Added `DeploymentAborted` event to stop running repeaters in the `DeploymentDomainService`
- Handling of the aborted event

fixes #381

### CODE REVIEW

File: SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift [hunk 1]
```diff
@@ -326,7 +331,7 @@ extension SafeCreationViewController {
         override var canCancel: Bool { return true }
         override var addressText: String? { return nil }
     }
-
+// idea tiger donor home sell offer fancy token pave blossom adapt alpha
```
Comment (sche) [inline SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift]: please remove

Comment (DmitryBespalov) [reply SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift]: oops 😊

**Review by sche — APPROVED** [review]
