### PR TITLE
GH-1233 fixes

### LINKED ISSUE #1233: Visual glitches in Address Book
- Opening address book shows content with delay
- Opening address book shows black background under search bar
- Opening entry has significant delay before content is shown

### PR DESCRIPTION
**Pull request by DmitryBespalov**
fixed

closes #1233

### CODE REVIEW

File: SafeUIKit/SafeUIKit/Components/QRCodeView/QRCodeView.swift [hunk 1]
```diff
@@ -26,24 +26,43 @@ final public class QRCodeView: BaseCustomView {
     }
 
     internal let imageView = UIImageView()
+    private let loadingLabel = UILabel()
```
Comment (sche) [inline SafeUIKit/SafeUIKit/Components/QRCodeView/QRCodeView.swift]: could you make it as activity indicator?

**Review by sche — APPROVED** [review]
