### PR TITLE
GH-1290 fixed migration

### LINKED ISSUE #1290: SQLiteStatement.swift line 72
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/16dfe96bd7f23d42809f1f56d609c875?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/16dfe96bd7f23d42809f1f56d609c875?utm_medium=service_hooks-github&utm_source=issue_impact)

### PR DESCRIPTION
**Pull request by DmitryBespalov**
fixed the SQL and added test

closes #1290

### CODE REVIEW

File: safe/safe/Migrations/M0009_MigrateSafesNamesToAddressBookTests.swift [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+        let adddressBookExpectedEntries: [[String]] = [
+            ["id1", "name", "address", "1"]
+        ]
+        XCTAssertEqual(addressBookActualEntries, adddressBookExpectedEntries)
+    }
+
+    func allEntries(of table: TableSchema) throws -> [[String]] {
+        try db.execute(sql: table.findAllSQL) { rs -> [String]? in
+            table.fields.map { field -> String in
+                rs[field.name] as String? ?? "<nil>"
```
Comment (sche) [inline safe/safe/Migrations/M0009_MigrateSafesNamesToAddressBookTests.swift:114]: nice

**Review by sche — APPROVED** [review]
