### PR TITLE
GH-1377 added notification processing

### LINKED ISSUE #1377: 2FA push doesn't open when opening app (not notification)
**Describe the bug**
- I have a Safe with Chrome extension as 2FA
- I'm using a dapp with the Chrome extension
- When the Safe app is open, the tx appears on my phone - all good ✅ 
- When the Safe app is closed, I get a notification, when I click it, the tx appears - all good ✅ 
- When the Safe app is closed, I get a notification, when I open the app from the home screen, the tx doesn't appear but the notification is clear - I have to resend 🚫 

**To Reproduce**
1. Use dapp with Chrome extension
2. Trigger tx
3. Get push on phone
4. Open Safe app (**don't** click on notification but open app from home screen)
-> Tx doesn't open.

**Expected behavior**
Tx opens I can can confirm/submit

**Smartphone (please complete the following information):**
- Device: iPhone SE
- iOS Version: 13.2
- App version: 1.11.0 (3) Production Mainnet

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Added processing of delivered notifications

closes #1377

### CODE REVIEW

File: safe/safe/AppDelegate.swift [hunk 1]
```diff
@@ -53,7 +53,6 @@ class AppDelegate: UIResponder, UIApplicationDelegate, Resettable {
         #endif
 
         createWindow()
-        UIApplication.shared.applicationIconBadgeNumber = 0
```
Comment (DmitryBespalov) [inline safe/safe/AppDelegate.swift:56]: I thought that this is handled in the willEnterForeground -> processsDeliveredNotifications

**Review by sche — APPROVED** [review]
